### ISSUE TITLE
Cache queries to Slack API

### ISSUE THREAD

**Issue by lbolla** [pmxbot/pmxbot#80]
`pmxbot` tries to resolve username and channels at every message, so it frequently hits Slack API's request limit (429 http error).
It should instead cache the return values for a while before refreshing.

**Comment by lbolla** [comment]
Full error:
```
Error resolving slack reference

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/pmxbot/slack.py", line 99, in _expand

    ref = resolvers[match_type](match_name)

  File "/usr/local/lib/python3.6/site-packages/slacker/__init__.py", line 206, in get_user_id

    members = self.list().body['members']

  File "/usr/local/lib/python3.6/site-packages/slacker/__init__.py", line 191, in list

    return self.get('users.list', params={'presence': int(presence)})

  File "/usr/local/lib/python3.6/site-packages/slacker/__init__.py", line 117, in get

    api, **kwargs

  File "/usr/local/lib/python3.6/site-packages/slacker/__init__.py", line 95, in _request

    response.raise_for_status()

  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://slack.com/api/users.list?presence=0&token=XXX
```

**Comment by jaraco** [comment]
See also os/slacker#133.

**Comment by jaraco** [comment]
Since no one has complained about this issue, I'm closing it as obsolete.
