### ISSUE TITLE
MongoDB srv scheme not detected

### ISSUE THREAD

**Issue by jaraco** [pmxbot/pmxbot#90]
I recently attempted to configure a bot instance with a `mongodb+srv://` scheme but it fails with:

```
Nov 14 18:31:22 kafka pmxbot[8421]: Traceback (most recent call last):
Nov 14 18:31:22 kafka pmxbot[8421]:   File "/opt/pmxbot/lib/python3.7/site-packages/pmxbot/core.py", line 646, in _load_library_exte
Nov 14 18:31:22 kafka pmxbot[8421]:     init_func()
Nov 14 18:31:22 kafka pmxbot[8421]:   File "/opt/pmxbot/lib/python3.7/site-packages/pmxbot_haiku/models.py", line 8, in init_models
Nov 14 18:31:22 kafka pmxbot[8421]:     HaikusSevens.initialize()
Nov 14 18:31:22 kafka pmxbot[8421]:   File "/opt/pmxbot/lib/python3.7/site-packages/pmxbot_haiku/models.py", line 17, in initialize
Nov 14 18:31:22 kafka pmxbot[8421]:     cls.store = cls.from_URI(pmxbot.config.database)
Nov 14 18:31:22 kafka pmxbot[8421]:   File "/opt/pmxbot/lib/python3.7/site-packages/pmxbot/storage.py", line 37, in from_URI
Nov 14 18:31:22 kafka pmxbot[8421]:     return next(matches)(URI)
Nov 14 18:31:22 kafka pmxbot[8421]: StopIteration
```

**Comment by jaraco** [comment]
After adding support for the scheme, when using it, the service fails to connect with this error:

```
pymongo.errors.ConfigurationError: The "dnspython" module must be installed to use mongodb+srv:
```
